# Task 3-1: Create 1-d numpy array

Write Python code to create  1-d Numpy arrays containing the values as follows

a)	[0,1,2,3,4,5,6,7]
b)	['Mary', 'John', 'Peter', 'Christine']
c)	['2017-10-01', '2017-10-02', '2017-10-03',….., '2017-10-31'] 
d)	10 random decimal numbers between 0  and 1

In [4]:
# task 3-1
import numpy as np

a = np.array([(0,1,2,3,4,5,6,7)])
b = np.array(['Mary', 'John', 'Peter', 'Christine'])
c = np.arange('2017-10-01','2017-11-01',dtype='datetime64')
d = np.arange(10)  

print(a)
print(b)
print(c)
print(d)

[[0 1 2 3 4 5 6 7]]
['Mary' 'John' 'Peter' 'Christine']
['2017-10-01' '2017-10-02' '2017-10-03' '2017-10-04' '2017-10-05'
 '2017-10-06' '2017-10-07' '2017-10-08' '2017-10-09' '2017-10-10'
 '2017-10-11' '2017-10-12' '2017-10-13' '2017-10-14' '2017-10-15'
 '2017-10-16' '2017-10-17' '2017-10-18' '2017-10-19' '2017-10-20'
 '2017-10-21' '2017-10-22' '2017-10-23' '2017-10-24' '2017-10-25'
 '2017-10-26' '2017-10-27' '2017-10-28' '2017-10-29' '2017-10-30'
 '2017-10-31']
[0 1 2 3 4 5 6 7 8 9]


In [9]:
# task 3-1

import numpy as np

a = np.arange(0,8)
b = np.array(['Mary', 'John', 'Peter', 'Christine'])
c = np.arange('2017-10-01','2017-11-01',dtype='datetime64')
d = np.arange(10)  

print(a)
print(b)
print(c)
print(d)

[0 1 2 3 4 5 6 7]
['Mary' 'John' 'Peter' 'Christine']
['2017-10-01' '2017-10-02' '2017-10-03' '2017-10-04' '2017-10-05'
 '2017-10-06' '2017-10-07' '2017-10-08' '2017-10-09' '2017-10-10'
 '2017-10-11' '2017-10-12' '2017-10-13' '2017-10-14' '2017-10-15'
 '2017-10-16' '2017-10-17' '2017-10-18' '2017-10-19' '2017-10-20'
 '2017-10-21' '2017-10-22' '2017-10-23' '2017-10-24' '2017-10-25'
 '2017-10-26' '2017-10-27' '2017-10-28' '2017-10-29' '2017-10-30'
 '2017-10-31']
[0 1 2 3 4 5 6 7 8 9]


# Task 3-2: Create 2-d numpy array 

Write Python code to create  2-d Numpy arrays containing the values as follows

a)	2x4 array [(1,2,3,4), (5,6,7,8)]
b)	3x3 array [(1.6,1.7,1.8),(2.5,5.0,7.5),(20,40,60)]
c)	3x4 2-d array, with initial value zero
d)	4x3 2-d array with initial value 10.5
e)	4x8 array with random values between 1 and 6

In [12]:
# task 3-2

import numpy as np

a = np.array([(1,2,3,4),
              (5,6,7,8)])

b = np.array([(1.6,1.7,1.8),
              (2.5,5.0,7.5),
              (20,40,60)])

c = np.zeros((3,4))

d = np.full((4,3), 10.5)

e = np.random.randint(1,7,(4,8))  

print(a)
print(b)
print(c)
print(d)
print(e)

[[1 2 3 4]
 [5 6 7 8]]
[[ 1.6  1.7  1.8]
 [ 2.5  5.   7.5]
 [20.  40.  60. ]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[10.5 10.5 10.5]
 [10.5 10.5 10.5]
 [10.5 10.5 10.5]
 [10.5 10.5 10.5]]
[[6 5 3 5 6 4 3 5]
 [3 4 1 3 5 1 3 4]
 [6 2 3 1 4 2 3 5]
 [1 3 4 3 1 3 2 4]]


# Task 4-1: Use the  shape, ndim, size properties and len function

Create 4 arrays with the values as shown in (a) to (d), then use the following properties and function on each array to inspect each one.  

•	shape property to find out the shape of the array
•	ndim property to find out the number of dimensions of the array
•	size property to find out the total number of elements in the array
•	len function to find out the number of rows in the array

(a)	[1.55,1.73,1.9,1.72,1.66,1.8]
(b)	 [('red', 'green', 'yellow', 'blue'),(True,False, False, True), ('2017-10-01', '2017-11-11', '2017-12-23', '2018-03-31')]
(c)	[[(10,9,8,7),(6,5,4,3)], [(1,2,3,4),(5,6,7,8)]]
	

In [19]:
# task 4-1

import numpy as np

a = np.array([1.55,1.73,1.9,1.72,1.66,1.8])

b = np.array([('red', 'green', 'yellow', 'blue'),
              (True,False, False, True), 
              ('2017-10-01', '2017-11-11', '2017-12-23', '2018-03-31')])
c = np.array([[(10,9,8,7),(6,5,4,3)],[(1,2,3,4),(5,6,7,8)]])


#shape returns the number of elements in each dimension
print('====shape====')
print(a.shape)
print(b.shape)
print(c.shape)  

#ndim property to find out the number of dimensions of the array
print('====ndim====')
print(a.ndim)
print(b.ndim)
print(c.ndim)

#size property to find out the total number of elements in the array
print('====size====')
print(a.size)
print(b.size)
print(c.size)


#len function to find out the number of rows in the array
print('====len====')
print(len(a))
print(len(b))
print(len(c))


====shape====
(6,)
(3, 4)
(2, 2, 4)
====ndim====
1
2
3
====size====
6
12
16
====len====
6
3
2


# Task 4-2: Use the type function, dtype property

Apply the type function and dtype property on each of the arrays in Task 2 to inspect them
 
Your output should appear as shown on the right.

In [47]:
# Task 4-2

print(f'type(a) is {type(a)} {a.dtype}')

print(f'type(b) is {type(a)} {a.dtype}')

print(f'type(c) is {type(a)} {a.dtype}')


type(a) is <class 'numpy.ndarray'> int32
type(b) is <class 'numpy.ndarray'> int32
type(c) is <class 'numpy.ndarray'> int32


# Task 5-1: Flatten an array

(a)	Write Python code to convert the multi-dimensional array a, into a 1-D array

a = np.array([ ['Mary', 'John','Bob'], 
               ['Zoe', 'Chris','Ann'],
               ['Leon', 'Kathy','Sam']])

In [22]:
# task 5-1
a = np.array([ ['Mary', 'John','Bob'], 
               ['Zoe', 'Chris','Ann'],
               ['Leon', 'Kathy','Sam']])


b = a.flatten()

print(a) 
print()
print(b)

[['Mary' 'John' 'Bob']
 ['Zoe' 'Chris' 'Ann']
 ['Leon' 'Kathy' 'Sam']]

['Mary' 'John' 'Bob' 'Zoe' 'Chris' 'Ann' 'Leon' 'Kathy' 'Sam']


# Task 5-2: Reshape arrays

(a)	Write Python code to convert the following 1-D array a into a 3x5 multi-dimensional array

a = np.arange(15,30)

(b)	Convert the following 2x6 array b into a 3x4 array

b = np.array([ [1,2,3,4,5,6], [7,8,9,10,11,12]])

In [28]:
# task 5-2
a = np.arange(15,30)
c = a.reshape((3,5))

print(a)
print()
print(c)
print()

b = np.array([ [1,2,3,4,5,6], [7,8,9,10,11,12]])
d = b.reshape((3,4))

print(b)
print()
print(d)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]

[[15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# Task 5-3: Transpose array

(a)	Write Python code to transpose the following array

a = np.array([ [1,2,3,4,5,6], [7,8,9,10,11,12]])

In [29]:
# Task 5-3

a = np.array([ [1,2,3,4,5,6], [7,8,9,10,11,12]])
b = a.transpose()
print(b)

[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]


In [30]:
a = np.array([ [1,2,3,4,5,6], [7,8,9,10,11,12]])
print(a.transpose())

[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]


# Task 6-1: Concatenate arrays
https://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html

(a)	Write Python code to concatenate the following arrays on the x-axis

a = np.array([[ 1,2,3],[ 4,5,6],[7,8,9]])

b = np.full((3,3),1.5)

c = np.arange(0,15).reshape(5,3)


(b)	Write Python code to concatenate the following arrays on the y-axis

a = np.array([[ 1,2,3,4],[ 4,5,6,7],[7,8,9,10],[11,12,13,14]])

b = np.random.randint(100,200,(4,6))

c = np.arange(0,40).reshape(4,10)

In [40]:
# **Task 6-1 (a)**
a = np.array([[ 1,2,3],[ 4,5,6],[7,8,9]])
b = np.full((3,3),1.5)
c = np.arange(0,15).reshape(5,3)

print(a)
print()
print(b)
print()
print(c)
print()
print(np.concatenate((a,b,c), axis=0))
print()

#r = np.concatenate((a,b,c), axis=0)
#print(r)

# **Task 6-1 (b)**
a = np.array([[ 1,2,3,4],[ 4,5,6,7],[7,8,9,10],[11,12,13,14]])
b = np.random.randint(100,200,(4,6))
c = np.arange(0,40).reshape(4,10)
print(a)
print()
print(b)
print()
print(c)
print()
print(np.concatenate((a,b,c), axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1.5 1.5 1.5]
 [1.5 1.5 1.5]
 [1.5 1.5 1.5]]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

[[ 1.   2.   3. ]
 [ 4.   5.   6. ]
 [ 7.   8.   9. ]
 [ 1.5  1.5  1.5]
 [ 1.5  1.5  1.5]
 [ 1.5  1.5  1.5]
 [ 0.   1.   2. ]
 [ 3.   4.   5. ]
 [ 6.   7.   8. ]
 [ 9.  10.  11. ]
 [12.  13.  14. ]]

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]
 [11 12 13 14]]

[[105 194 169 127 150 185]
 [133 117 108 103 107 180]
 [197 171 197 185 178 110]
 [120 108 111 101 195 104]]

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]

[[  1   2   3   4 105 194 169 127 150 185   0   1   2   3   4   5   6   7
    8   9]
 [  4   5   6   7 133 117 108 103 107 180  10  11  12  13  14  15  16  17
   18  19]
 [  7   8   9  10 197 171 197 185 178 110  20  21  22  23  24  25  26  27
   28  29]
 [ 11  12  13  14 120 108 111 101 195 104  30  31  32  33  34  35  36  37
   38  39]]


# Task 6-2: Split arrays
https://docs.scipy.org/doc/numpy/reference/generated/numpy.split.html#numpy.split

(a)	Write Python code to split the following array into 20 sub-arrays

x = np.arange(100)

(b)	Write Python code to split the following array at these intervals: 10, 25, 45, 75, 95

x = np.arange(100)

In [45]:
# Task 6-2 (a)
x = np.arange(100)
print(x)
print()
print(np.split(x,20))
print()

# Task 6-2 (b)
x = np.arange(100)
print(np.split(x,(10,25,45,75,95)))
print(np.split(x,[10,25,45,75,95]))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14]), array([15, 16, 17, 18, 19]), array([20, 21, 22, 23, 24]), array([25, 26, 27, 28, 29]), array([30, 31, 32, 33, 34]), array([35, 36, 37, 38, 39]), array([40, 41, 42, 43, 44]), array([45, 46, 47, 48, 49]), array([50, 51, 52, 53, 54]), array([55, 56, 57, 58, 59]), array([60, 61, 62, 63, 64]), array([65, 66, 67, 68, 69]), array([70, 71, 72, 73, 74]), array([75, 76, 77, 78, 79]), array([80, 81, 82, 83, 84]), array([85, 86, 87, 88, 89]), array([90, 91, 92, 93, 94]), array([95, 96, 97, 98, 99])]

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]), array([25, 2

# Task 7-1: Make a copy of a Numpy array

(a)	What is the difference between y and z?

x = np.array([1, 2, 3])

y = x

z = np.copy(x)

(b)	What is the value of x, y and z after executing Line 4?

Line	
1	x = np.array([1, 2, 3])

2	y = x

3	z = np.copy(x)

4	x[0] = 10

In [3]:
# Task 7-1 (a)

import numpy as np

x = np.array([1, 2, 3])

y = x

z = np.copy(x)

print(y)
print(z)

[1 2 3]
[1 2 3]


In [4]:
# Task 7-1 (b)

x = np.array([1, 2, 3])

y = x

z = np.copy(x)

x[0] = 10

print(x)
print(y)
print(z)

[10  2  3]
[10  2  3]
[1 2 3]


# task 8-1	Sorting arrays
Task 1: Basic sorting
(a)	Write Python code to sort the following 1-d array using the sort method

arr_1 = np.random.randint(100,200,10)

Your output should be similar to that below.

(b)	Write Python code to sort the following 2-d array by columns

arr_2 = np.random.randint(1,20,(3,5))

Your output should be similar to that below.

(c)	Write Python code to sort the following 2-d array by rows without affecting the original .

arr_3 = np.random.randint(100,200,(2,5))


In [5]:
# task 8-1 (a)

arr_1 = np.random.randint(100,200,10)

print('before sorting')
print(arr_1)

arr_1.sort()
print('after sorting')
print(arr_1)

before sorting
[129 195 105 157 162 186 101 177 136 187]
after sorting
[101 105 129 136 157 162 177 186 187 195]


In [10]:
# task 8-1 (b)

arr_2 = np.random.randint(1,20,(3,5))

print('before sorting')
print(arr_2)

arr_2.sort(axis=0) # try rr_2.sort(axis=1) 
print('after sorting axis=0')
print(arr_2)

before sorting
[[ 1 12  9 17  3]
 [ 2  4  6  1  2]
 [ 2  8 16 19  2]]
after sorting axis=0
[[ 1  4  6  1  2]
 [ 2  8  9 17  2]
 [ 2 12 16 19  3]]


In [11]:
arr_2.sort(axis=1) 
print('after sorting axis=1')
print(arr_2)

after sorting axis=1
[[ 1  1  2  4  6]
 [ 2  2  8  9 17]
 [ 2  3 12 16 19]]


In [14]:
# task 8-1 (c)

arr_3 = np.random.randint(100,200,(2,5))
arr_3_copy = np.copy(arr_3)

print('before sorting - original array')
print(arr_3)

arr_3.sort()  # default axis=1
print('after sorting - original array')
print(arr_3)

arr_3_copy.sort()
print('after sorting - copy array')
print(arr_3_copy)

before sorting - original array
[[102 132 185 106 158]
 [191 156 117 199 120]]
after sorting - original array
[[102 106 132 158 185]
 [117 120 156 191 199]]
after sorting - copy array
[[102 106 132 158 185]
 [117 120 156 191 199]]


In [29]:
arr_3.sort(axis=0)
print('after sorting axis=0')
print(arr_3)

after sorting axis=0
[[114 119 120 120 153]
 [135 145 158 180 195]]


In [31]:
arr_3.sort(axis=1)
print('after sorting axis=1')
print(arr_3)

after sorting axis=1
[[114 119 120 120 153]
 [135 145 158 180 195]]


# Task 9.	Subsetting and Indexing

In [18]:
# task 9-1
a = np.arange(1,100,1)
b = np.array([[1,2,3,4], [100,200,300,400],  [5,6,7,8],  [9,10,11,12] ])

print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]
[[  1   2   3   4]
 [100 200 300 400]
 [  5   6   7   8]
 [  9  10  11  12]]


In [20]:
# task 9-1 (a)
print(a[3])
print(b[3])

4
[ 9 10 11 12]


In [21]:
# task 9-1 (b)
print(b[1:3])

[[100 200 300 400]
 [  5   6   7   8]]


In [23]:
# task 9-1 (c)
print(b[:,-1])

[  4 400   8  12]


In [31]:
# task 9-1 (d)
print(b[1,0],b[1,-1])

100 400


In [42]:
# task 9-1 (d)
print(b[1,[0,-1]])

[100 400]


In [32]:
# task 9-1 (e)
print(b[2:,1:])

[[ 6  7  8]
 [10 11 12]]


In [35]:
# task 9-1 (f)
a = np.arange(10,20,2)
print(a)

[10 12 14 16 18]


In [41]:
# task 9-1 (g)
print(a[::-1])

[18 16 14 12 10]


# Task 9-2: Boolean indexing

In [49]:
a = np.array((np.arange(0,10),
             np.arange(10,20),
             np.arange(20,30),
             np.arange(30,40)))

b = np.random.randint(100,200,(3,3))

print(a)
print(b)

a1 = a % 2 == 0
arr_a = a[a1]

print(arr_a)

b1 = b >150
arr_b = b[b1]
print(arr_b)


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]
[[197 148 101]
 [107 147 115]
 [160 192 134]]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]
[197 160 192]


In [50]:
# task 9-2

print(a[a%2==0])
print()
print(b[b>150])

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38]

[197 160 192]


In [130]:
# task 9-3
b = np.arange(9.).reshape(3, 3)
b5 = np.where(b > 5)

print(b)
print(b[b>5])
print()
print(b5)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[6. 7. 8.]

(array([2, 2, 2], dtype=int64), array([0, 1, 2], dtype=int64))


In [131]:
a = np.arange(10)
b = np.where( a>5 )
print(a)
print(b)
np.where(a < 5, a, 10*a)

[0 1 2 3 4 5 6 7 8 9]
(array([6, 7, 8, 9], dtype=int64),)


array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

# 10.	Array Math

In [103]:
# task 10-1
a = np.arange(100,200,1).reshape(20,5) 
b = np.arange(1,2000,20).reshape(10,10) 
c = np.array([ [1,2,3], [4,5,6]])

#print(a)
#print(b)
#print(c)

# print(a+b) # task 10-1 (a) - a+b doesn't work because they have different hape  

# (b)
a2 = np.random.randint(0,100,(20,5))
print(a+a2)

# (c) 
b1 = np.random.randint(b.min(),b.max(),(2,3))  # get the random element.
#print(b1)
print(b1-c)

# (d)
c2 = np.array(c*10)   # or c2 =c*10
print(c2)

[[103 187 106 198 107]
 [179 160 162 150 206]
 [151 172 192 203 152]
 [119 174 134 146 218]
 [129 177 169 188 136]
 [155 208 217 196 145]
 [162 145 156 208 229]
 [217 196 143 195 208]
 [236 218 234 162 154]
 [192 228 177 243 215]
 [166 172 239 165 184]
 [196 220 202 224 212]
 [251 260 244 239 259]
 [260 210 169 249 240]
 [250 208 270 237 230]
 [192 227 190 188 201]
 [272 236 239 186 205]
 [253 214 266 242 285]
 [247 213 261 287 255]
 [260 266 260 203 250]]
[[ 935 1851 1344]
 [1523  989 1855]]
[[10 20 30]
 [40 50 60]]


# 11.	Statistical methods


In [110]:
# task 11-1
a = np.array((np.arange(0,10),
             np.arange(10,20),
             np.arange(20,30),
             np.arange(30,40)))
print(a)

# (a)
print(f'*** Sume of all numbers in a ***')
print(np.sum(a))

# (b)
print(f'*** Mean of all numbers in a ***')
print(np.mean(a))

# (c)
print(f'*** Sum of all numbers in each row of a ***')
print(np.sum(a,axis=1))

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]
*** Sume of all numbers in a ***
780
*** Mean of all numbers in a ***
19.5
*** Sum of all numbers in each row of a ***
[ 45 145 245 345]


In [114]:
# task 11-2
a = np.arange(100,200,0.5)
b = np.arange(100,200,0.1)

# (a)
print(np.std(a))
print(np.std(b))

# (b)
print(np.var(a))
print(np.var(b))

28.86715261330774
28.867499025719308
833.3125
833.3324999999053


In [132]:
# task 11-3
a = np.random.randint(1,1000,(3,4))

print(a)
print(a.max(axis=1))
print(a.max())

print(a)
print(a.min(axis=0))
print(a.min())

[[129 834 627 865]
 [ 87 543 875 399]
 [410 993 585 665]]
[865 875 993]
993
[[129 834 627 865]
 [ 87 543 875 399]
 [410 993 585 665]]
[ 87 543 585 399]
87
