In [2]:
import numpy as np
import pandas as pd

# Task 2.	Create Pandas Series

In [27]:
# task 2-1 (a) : Create Pandas Series
s1 = pd.Series([1.0,3.0,5.0,None,6.0,8.0])
print(s1)

# task 2-1 (b)
s2 = pd.Series([1.0,3.0,5.0,None,6.0,8.0],index=['a', 'b', 'c', 'd', 'e', 'f'])
print(s2)

# task 2-1 (c)
ser_3 = {'Indonesia':'Melati Putih', 'Malaysia':'Hibiscus rosa-sinensis', 'Phillippines':'Sampaguita', 'Singapore':'Vanda Miss Joaquim'}
s3 = pd.Series(ser_3)
print(s3)

# task 2-1 (d)
s4 = pd.Series(pd.date_range('2017-10-1','2017-10-15'))
print(pd.date_range('2017-10-1','2017-10-15')) # or using numpy arange: np.arange('2017-10-01','2017-10-15',dtype='datetime64')
print(s4)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64
a    1.0
b    3.0
c    5.0
d    NaN
e    6.0
f    8.0
dtype: float64
Indonesia                 Melati Putih
Malaysia        Hibiscus rosa-sinensis
Phillippines                Sampaguita
Singapore           Vanda Miss Joaquim
dtype: object
DatetimeIndex(['2017-10-01', '2017-10-02', '2017-10-03', '2017-10-04',
               '2017-10-05', '2017-10-06', '2017-10-07', '2017-10-08',
               '2017-10-09', '2017-10-10', '2017-10-11', '2017-10-12',
               '2017-10-13', '2017-10-14', '2017-10-15'],
              dtype='datetime64[ns]', freq='D')
0    2017-10-01
1    2017-10-02
2    2017-10-03
3    2017-10-04
4    2017-10-05
5    2017-10-06
6    2017-10-07
7    2017-10-08
8    2017-10-09
9    2017-10-10
10   2017-10-11
11   2017-10-12
12   2017-10-13
13   2017-10-14
14   2017-10-15
dtype: datetime64[ns]


# Task-3.	Create Pandas DataFrames

In [64]:
# task 3-1 (a)
df1 = pd.DataFrame(np.random.randint(100,200,(5,5)))
df1

0    1    2    3    4
0  140  173  154  144  177
1  179  193  170  124  174
2  122  164  185  164  165
3  140  123  122  183  123
4  123  157  164  186  101

In [65]:
# task 3-1 (a)
data = np.random.randint(100,200,(5,5))
df1 = pd.DataFrame(data)
                         
print(data)
df1

[[167 186 155 194 138]
 [170 130 152 184 158]
 [140 191 188 124 141]
 [159 183 109 108 168]
 [130 199 196 166 155]]


0    1    2    3    4
0  167  186  155  194  138
1  170  130  152  184  158
2  140  191  188  124  141
3  159  183  109  108  168
4  130  199  196  166  155

In [66]:
# task 3-1 (b)
df2 = pd.DataFrame(np.random.randint(100,200,(5,5)),columns=['Team 1', 'Team 2', 'Team 3', 'Team 4', 'Team 5'], index=['Game 1', 'Game 2', 'Game 3', 'Game 4', 'Game 5'])
df2

Team 1  Team 2  Team 3  Team 4  Team 5
Game 1     139     132     185     127     191
Game 2     151     191     196     147     131
Game 3     122     191     126     185     111
Game 4     106     199     103     126     175
Game 5     100     138     104     106     184

In [68]:
# task 3-1 (c)
uni_graduates = {
    2010:{'Females':6300,'Males':6496}, 2011:{'Females':7281,'Males':6428},
    2012:{'Females':7114,'Males':6736}, 2013:{'Females':8170,'Males':7785},
    2014:{'Females':7620,'Males':7756}
}

print(uni_graduates)
print()
df3 = pd.DataFrame(uni_graduates)
print(df3); print(type(df3))

{2010: {'Females': 6300, 'Males': 6496}, 2011: {'Females': 7281, 'Males': 6428}, 2012: {'Females': 7114, 'Males': 6736}, 2013: {'Females': 8170, 'Males': 7785}, 2014: {'Females': 7620, 'Males': 7756}}

         2010  2011  2012  2013  2014
Females  6300  7281  7114  8170  7620
Males    6496  6428  6736  7785  7756
<class 'pandas.core.frame.DataFrame'>


In [72]:
# task 3-1 (d)
nus_median_gross_pay_2013to2015 = {
'BA' : [3000,3000,3000],
'BA (Honours)' : [3200,3520,3800],
'BA (Accountancy)' : [2700,2838,2850],
'BA (Accountancy) (Honours)' : [2800,2912,3000]
}

df4 = pd.DataFrame(nus_median_gross_pay_2013to2015, index=['2013', '2014', '2015'])
print(df4)
print(type(df4))

        BA  BA (Honours)  BA (Accountancy)  BA (Accountancy) (Honours)
2013  3000          3200              2700                        2800
2014  3000          3520              2838                        2912
2015  3000          3800              2850                        3000
<class 'pandas.core.frame.DataFrame'>


In [79]:
# task 3-1 (e)
jan = pd.date_range('20170101', periods=31)
mar = pd.date_range('20170301', periods=31)
may = pd.date_range('20170501', periods=31)
jul = pd.date_range('20170701', periods=31)
aug = pd.date_range('20170801', periods=31)
oct = pd.date_range('20171001', periods=31)
dec = pd.date_range('20171201', periods=31)

monthswith31days = {"Jan": jan, "Mar": mar,"May": may, "Jul": jul,"Aug": aug, "Oct": oct, "Dec": dec}

df5 = pd.DataFrame(monthswith31days)
df5

Jan        Mar        May        Jul        Aug        Oct  \
0  2017-01-01 2017-03-01 2017-05-01 2017-07-01 2017-08-01 2017-10-01   
1  2017-01-02 2017-03-02 2017-05-02 2017-07-02 2017-08-02 2017-10-02   
2  2017-01-03 2017-03-03 2017-05-03 2017-07-03 2017-08-03 2017-10-03   
3  2017-01-04 2017-03-04 2017-05-04 2017-07-04 2017-08-04 2017-10-04   
4  2017-01-05 2017-03-05 2017-05-05 2017-07-05 2017-08-05 2017-10-05   
5  2017-01-06 2017-03-06 2017-05-06 2017-07-06 2017-08-06 2017-10-06   
6  2017-01-07 2017-03-07 2017-05-07 2017-07-07 2017-08-07 2017-10-07   
7  2017-01-08 2017-03-08 2017-05-08 2017-07-08 2017-08-08 2017-10-08   
8  2017-01-09 2017-03-09 2017-05-09 2017-07-09 2017-08-09 2017-10-09   
9  2017-01-10 2017-03-10 2017-05-10 2017-07-10 2017-08-10 2017-10-10   
10 2017-01-11 2017-03-11 2017-05-11 2017-07-11 2017-08-11 2017-10-11   
11 2017-01-12 2017-03-12 2017-05-12 2017-07-12 2017-08-12 2017-10-12   
12 2017-01-13 2017-03-13 2017-05-13 2017-07-13 2017-08-13 2017-10-13   
13 2017-01-14 2017-03-14 2017-05-14 2017-07-14 2017-08-14 2017-10-14   
14 2017-01-15 2017-03-15 2017-05-15 2017-07-15 2017-08-15 2017-10-15   
15 2017-01-16 2017-03-16 2017-05-16 2017-07-16 2017-08-16 2017-10-16   
16 2017-01-17 2017-03-17 2017-05-17 2017-07-17 2017-08-17 2017-10-17   
17 2017-01-18 2017-03-18 2017-05-18 2017-07-18 2017-08-18 2017-10-18   
18 2017-01-19 2017-03-19 2017-05-19 2017-07-19 2017-08-19 2017-10-19   
19 2017-01-20 2017-03-20 2017-05-20 2017-07-20 2017-08-20 2017-10-20   
20 2017-01-21 2017-03-21 2017-05-21 2017-07-21 2017-08-21 2017-10-21   
21 2017-01-22 2017-03-22 2017-05-22 2017-07-22 2017-08-22 2017-10-22   
22 2017-01-23 2017-03-23 2017-05-23 2017-07-23 2017-08-23 2017-10-23   
23 2017-01-24 2017-03-24 2017-05-24 2017-07-24 2017-08-24 2017-10-24   
24 2017-01-25 2017-03-25 2017-05-25 2017-07-25 2017-08-25 2017-10-25   
25 2017-01-26 2017-03-26 2017-05-26 2017-07-26 2017-08-26 2017-10-26   
26 2017-01-27 2017-03-27 2017-05-27 2017-07-27 2017-08-27 2017-10-27   
27 2017-01-28 2017-03-28 2017-05-28 2017-07-28 2017-08-28 2017-10-28   
28 2017-01-29 2017-03-29 2017-05-29 2017-07-29 2017-08-29 2017-10-29   
29 2017-01-30 2017-03-30 2017-05-30 2017-07-30 2017-08-30 2017-10-30   
30 2017-01-31 2017-03-31 2017-05-31 2017-07-31 2017-08-31 2017-10-31   

          Dec  
0  2017-12-01  
1  2017-12-02  
2  2017-12-03  
3  2017-12-04  
4  2017-12-05  
5  2017-12-06  
6  2017-12-07  
7  2017-12-08  
8  2017-12-09  
9  2017-12-10  
10 2017-12-11  
11 2017-12-12  
12 2017-12-13  
13 2017-12-14  
14 2017-12-15  
15 2017-12-16  
16 2017-12-17  
17 2017-12-18  
18 2017-12-19  
19 2017-12-20  
20 2017-12-21  
21 2017-12-22  
22 2017-12-23  
23 2017-12-24  
24 2017-12-25  
25 2017-12-26  
26 2017-12-27  
27 2017-12-28  
28 2017-12-29  
29 2017-12-30  
30 2017-12-31

In [90]:
# task 3-1 (f)
npArray = np.random.randn(6,4)
print(npArray)

df6 = pd.DataFrame(npArray, index=[np.arange('2013-01-01','2013-01-07',dtype='datetime64')], columns=['A','B','C','D'])
df6

[[ 0.59808387 -1.40379391 -0.54586017 -0.08874299]
 [ 0.06152116  2.24498434  0.41465895  1.20902562]
 [-0.71557502 -0.51510051 -0.2558798   0.51807961]
 [-1.4840056  -0.62623322  0.39697086  1.24799579]
 [-0.52135121 -0.81173203  0.90654071  0.985329  ]
 [-1.38826845  3.04477857  0.06257033  0.03575473]]


A         B         C         D
2013-01-01  0.598084 -1.403794 -0.545860 -0.088743
2013-01-02  0.061521  2.244984  0.414659  1.209026
2013-01-03 -0.715575 -0.515101 -0.255880  0.518080
2013-01-04 -1.484006 -0.626233  0.396971  1.247996
2013-01-05 -0.521351 -0.811732  0.906541  0.985329
2013-01-06 -1.388268  3.044779  0.062570  0.035755

In [86]:
?np.random.randn

# Task 4.	View data

In [92]:
# task 4A-1

myseries = pd.Series(np.random.random(1000))

mydf = pd.DataFrame({'A': np.random.randint(10,100,1000),
                     'B': 0,
                     'C': np.arange(1000)})

In [93]:
#  task 4A-1 (a)
print(myseries.shape)
print(myseries.index)
print(myseries.values)
print(myseries.count())
print(myseries.describe())

(1000,)
RangeIndex(start=0, stop=1000, step=1)
[4.42801455e-01 9.42050931e-01 9.76191708e-01 2.93707921e-02
 3.26114195e-01 7.38030234e-01 2.24144988e-01 9.29963407e-01
 1.62902448e-02 6.72214900e-01 1.52948475e-01 8.88003033e-01
 2.27711310e-01 6.24533150e-01 5.92735117e-02 6.05588919e-02
 2.68990994e-01 8.94191859e-01 1.77832177e-01 9.45441420e-01
 6.93500358e-01 9.84613797e-01 8.68198348e-01 5.14639986e-01
 7.29521350e-01 5.31568435e-01 4.92384254e-01 5.73744406e-01
 3.08342156e-01 6.06525103e-01 4.94353375e-01 5.59278430e-01
 6.86880045e-01 5.94214211e-01 6.66499278e-01 6.19590867e-01
 6.90329189e-01 7.82745869e-01 3.63348827e-01 7.13966564e-01
 2.56959715e-01 6.75109634e-01 1.21932307e-01 8.01169933e-01
 7.55179027e-01 7.92666828e-01 6.93738291e-01 4.24719936e-01
 6.04179609e-01 6.59898611e-01 1.38926395e-01 5.06095437e-01
 8.81985378e-01 7.62749040e-01 3.94272172e-01 7.82721878e-01
 1.22561386e-01 8.67735430e-01 4.52644654e-01 1.34192122e-01
 2.08144022e-02 2.75088040e-01 7.65426

In [94]:
#  task 4A-2 (b)
print(mydf.shape)
print(mydf.index)
print(mydf.columns)
print(mydf.count())
print(mydf.count())
print(mydf.values)
print(mydf.info())

(1000, 3)
RangeIndex(start=0, stop=1000, step=1)
Index(['A', 'B', 'C'], dtype='object')
A    1000
B    1000
C    1000
dtype: int64
A    1000
B    1000
C    1000
dtype: int64
[[ 16   0   0]
 [ 69   0   1]
 [ 60   0   2]
 ...
 [ 81   0 997]
 [ 53   0 998]
 [ 90   0 999]]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       1000 non-null   int32
 1   B       1000 non-null   int64
 2   C       1000 non-null   int32
dtypes: int32(2), int64(1)
memory usage: 15.8 KB
None


In [27]:
# Task 4B-1 Task 1: Display statistical information of Series and DataFrame
# Use all of the above methods to retrieve summary statistical information about myseries. 

print('Sum of myseries')
print(myseries.sum())
print('CumSum of myseries')
print(myseries.cumsum())
print('Min of myseries')
print(myseries.min())
print('Max of myseries')
print(myseries.max())
print('min index of myseries')
print(myseries.idxmin())
print('max index of myseries')
print(myseries.idxmax())
print('mean value of myseries')
print(myseries.mean())
print('median value of myseries')
print(myseries.median())
print('describe of myseries')
print(myseries.describe())

Sum of myseries
502.9727280297499
CumSum of myseries
0        0.913468
1        1.593937
2        2.549084
3        2.721894
4        3.430368
          ...    
995    501.341260
996    501.716414
997    502.235053
998    502.744042
999    502.972728
Length: 1000, dtype: float64
Min of myseries
0.0003400531697014264
Max of myseries
0.9988550984280171
min index of myseries
726
max index of myseries
159
mean value of myseries
0.5029727280297493
median value of myseries
0.5019166699054374
describe of myseries
count    1000.000000
mean        0.502973
std         0.289320
min         0.000340
25%         0.260571
50%         0.501917
75%         0.746109
max         0.998855
dtype: float64


# task 4B -2 : Display statistical information of Series and DataFrame

In [95]:
print('Sum of mydf')
print(mydf.sum())
print('CumSum of mydf')
print(mydf.cumsum())
print('Min of mydf')
print(mydf.min())
print('Max of mydf')
print(mydf.max())
print('min index of mydf')
print(mydf.idxmin())
print('max index of mydf')
print(mydf.idxmax())
print('mean value of mydf')
print(mydf.mean())
print('median value of mydf')
print(mydf.median())
print('describe of mydf')
print(mydf.describe())

Sum of mydf
A     53840
B         0
C    499500
dtype: int64
CumSum of mydf
         A  B       C
0       16  0       0
1       85  0       1
2      145  0       3
3      163  0       6
4      206  0      10
..     ... ..     ...
995  53547  0  495510
996  53616  0  496506
997  53697  0  497503
998  53750  0  498501
999  53840  0  499500

[1000 rows x 3 columns]
Min of mydf
A    10
B     0
C     0
dtype: int64
Max of mydf
A     99
B      0
C    999
dtype: int64
min index of mydf
A    91
B     0
C     0
dtype: int64
max index of mydf
A     22
B      0
C    999
dtype: int64
mean value of mydf
A     53.84
B      0.00
C    499.50
dtype: float64
median value of mydf
A     53.0
B      0.0
C    499.5
dtype: float64
describe of mydf
                 A       B            C
count  1000.000000  1000.0  1000.000000
mean     53.840000     0.0   499.500000
std      26.254594     0.0   288.819436
min      10.000000     0.0     0.000000
25%      31.000000     0.0   249.750000
50%      53.000000     0.

# Task 5.	Loading and Saving Datasets

In [97]:
# task 5-1: loading data
df_csv = pd.DataFrame(pd.read_csv('data/income.csv', sep=';'))
df_csv

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  47215  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [102]:
df_csv.shape

(5, 11)

In [105]:
df_csv.dtypes

GEOID    object
State    object
2005      int64
2006      int64
2007      int64
2008      int64
2009      int64
2010      int64
2011      int64
2012      int64
2013      int64
dtype: object

In [110]:
# task 5-2 : saving data
mydf = pd.DataFrame(np.random.randint(100,200,(5,5)),columns=['Team 1', 'Team 2', 'Team 3', 'Team 4', 'Team 5'], 
                    index=['Game 1', 'Game 2', 'Game 3', 'Game 4', 'Game 5'])
mydf

Team 1  Team 2  Team 3  Team 4  Team 5
Game 1     161     139     139     178     137
Game 2     158     176     183     139     153
Game 3     145     171     118     138     154
Game 4     170     192     102     120     131
Game 5     187     116     197     142     102

In [114]:
import os
os.getcwd()

'C:\\Users\\mingj\\Desktop\\PDS\\Topic3'

In [116]:
mydf.to_csv('data/mydf.csv')

In [117]:
mydf.to_excel('data/mydf.xlsx')

# task 6.	Selection

In [118]:
# task 6A-1

mydf = pd.read_excel('data/singstats_maritalstatus.xlsx', index_col='Variables')
df_1986 = mydf['1986']
df_1980s = mydf.loc[:, '1980':'1989']
df_1986
df_1980s

1980 1981 1982     1983     1984     1985     1986  \
Variables                                                                    
Total                1651500    -    -  1791900  1829000  1866700  1906600   
Single                674100    -    -   728000   714300   726600   736500   
Married               864600    -    -   951200  1005100  1020100  1039700   
Widowed                97100    -    -   101700    92800    99200   108200   
Divorced/ Separated    15800    -    -    11000    16700    20800    22300   
Males                 833500    -    -   901700   912200   929800   948000   
Single                375800    -    -   404700   393400   400100   408100   
Married               435900    -    -   476300   499600   506500   517100   
Widowed                16000    -    -    16600    13600    16200    15500   
Divorced/ Separated     5700    -    -     4100     5600     7000     7300   
Females               818000    -    -   890200   916800   936900   958600   
Single                298300    -    -   323400   321000   326500   328400   
Married               428700    -    -   474800   505500   513700   522600   
Widowed                81100    -    -    85100    79200    83000    92700   
Divorced/ Separated    10100    -    -     6900    11100    13700    15000   

                        1987     1988     1989  
Variables                                       
Total                1947600  1990000  2032400  
Single                735200   745700   752800  
Married              1083300  1112200  1137800  
Widowed               106900   108100   116200  
Divorced/ Separated    22200    24100    25700  
Males                 974100   994400  1007900  
Single                410800   416100   418000  
Married               539600   553300   563800  
Widowed                16100    17000    17900  
Divorced/ Separated     7700     8000     8200  
Females               973400   995600  1024500  
Single                324400   329600   334800  
Married               543700   558900   573900  
Widowed                90800    91100    98300  
Divorced/ Separated    14600    16000    17500

In [37]:
# task 6A-2

mydf = pd.read_excel('data/singstats_maritalstatus_2006_to_2016.xlsx', index_col='Variables')
df_index123 = mydf.iloc[:, 1:4]
print(df_index123)
df_last5cols = mydf.iloc[:, -5:]
print(df_last5cols)

                        2007     2008     2009
Variables                                     
Total                2944600  2938800  3034800
Single                918400   918700   957600
Married              1787100  1783700  1831300
Widowed               155600   146900   152700
Divorced/ Separated    83600    89500    93200
Males                1438300  1437200  1477500
Single                487500   488900   505100
Married               894700   896300   913300
Widowed                26400    22700    26600
Divorced/ Separated    29700    29300    32400
Females              1506400  1501600  1557300
Single                430900   429800   452400
Married               892400   887400   918000
Widowed               129100   124200   126000
Divorced/ Separated    53900    60100    60800
                        2012     2013     2014     2015     2016
Variables                                                       
Total                3183000  3205900  3259800  3275900  3318500
Single

In [14]:
# task 6A-3

mydf = pd.read_excel('data/singstats_maritalstatus.xlsx', index_col='Variables')

print(f'*** Data in 1980 column ***')
print(mydf['1980'])
print()

greater_500000 = mydf['1980']>500000
less_500000 = mydf['1980']<500000

print(f'Number of rows more than 500000 is {greater_500000.sum()}')
print(f'Number of rows values less than 500000 is {less_500000.sum()}')

mydf[greater_500000]

*** Data in 1980 column ***
Variables
Total                  1651500
Single                  674100
Married                 864600
Widowed                  97100
Divorced/ Separated      15800
Males                   833500
Single                  375800
Married                 435900
Widowed                  16000
Divorced/ Separated       5700
Females                 818000
Single                  298300
Married                 428700
Widowed                  81100
Divorced/ Separated      10100
Name: 1980, dtype: int64

Number of rows more than 500000 is 5
Number of rows values less than 500000 is 10


1980 1981 1982     1983     1984     1985     1986     1987  \
Variables                                                                   
Total      1651500    -    -  1791900  1829000  1866700  1906600  1947600   
Single      674100    -    -   728000   714300   726600   736500   735200   
Married     864600    -    -   951200  1005100  1020100  1039700  1083300   
Males       833500    -    -   901700   912200   929800   948000   974100   
Females     818000    -    -   890200   916800   936900   958600   973400   

              1988     1989  ...     2007     2008     2009     2010     2011  \
Variables                    ...                                                
Total      1990000  2032400  ...  2944600  2938800  3034800  3105700  3148700   
Single      745700   752800  ...   918400   918700   957600  1000500  1012000   
Married    1112200  1137800  ...  1787100  1783700  1831300  1844600  1875900   
Males       994400  1007900  ...  1438300  1437200  1477500  1517400  1534200   
Females     995600  1024500  ...  1506400  1501600  1557300  1588300  1614500   

              2012     2013     2014     2015     2016  
Variables                                               
Total      3183000  3205900  3259800  3275900  3318500  
Single     1022600  1029300  1048100  1034500  1049200  
Married    1899000  1911500  1940100  1945600  1974700  
Males      1550000  1560900  1583900  1589600  1607500  
Females    1633000  1645000  1675900  1686300  1711000  

[5 rows x 37 columns]

In [58]:
greater_500000 = mydf['1980']>500000
mydf[greater_500000][['1980','1981','1982']]

1980 1981 1982
Variables                   
Total      1651500    -    -
Single      674100    -    -
Married     864600    -    -
Males       833500    -    -
Females     818000    -    -

In [128]:
# task 6B-1
df_rainfall = pd.DataFrame(pd.read_csv('data/rainfall-monthly-total.csv', index_col='month'))

df_rainfall.loc['1982-01':'1982-12']

# df_rainfall_1982 = df_rainfall.loc['1982-01':'1982-12']
# df_rainfall_1982

total_rainfall
month                  
1982-01           107.1
1982-02            27.8
1982-03           160.8
1982-04           157.0
1982-05           102.2
1982-06            59.5
1982-07            76.3
1982-08           169.5
1982-09            54.1
1982-10            39.3
1982-11           134.0
1982-12           494.1

In [142]:
# task 6B-2
df_rainfall = pd.DataFrame(pd.read_csv('data/rainfall-monthly-total.csv', index_col='month'))

df_rainfall_last12rows = df_rainfall.iloc[-12:]  # 0r df_rainfall.iloc[-12::]
df_rainfall_last12rows

total_rainfall
month                  
2016-07           168.6
2016-08           139.2
2016-09           118.9
2016-10           181.0
2016-11           290.2
2016-12           292.6
2017-01           197.6
2017-02           158.4
2017-03           136.2
2017-04           208.6
2017-05           190.0
2017-06           106.0

In [145]:
# task 6B-3
df_rainfall = pd.DataFrame(pd.read_csv('data/rainfall-monthly-total.csv', index_col='month'))

df_rainfall_300 = df_rainfall[df_rainfall.total_rainfall>300]

df_rainfall_300 = df_rainfall_300.sort_values(by="total_rainfall")
df_rainfall_300.iloc[-12:]

total_rainfall
month                  
2007-12           468.6
1984-02           470.4
1992-11           474.3
1991-12           492.3
1982-12           494.1
1992-12           502.7
1989-11           508.4
2011-01           513.2
1987-01           568.6
2004-01           600.9
2001-12           609.0
2006-12           765.9

# 7.	Reshaping data 

In [66]:
# task 7A-1
df = pd.DataFrame(pd.read_csv('data/graduate-employment-survey-ntu-nus-sit-smu-sutd-utf8.csv'))

df1 = df.drop(['school', 'employment_rate_overall', 'employment_rate_permanent', 'basic_monthly_mean', 
              'basic_monthly_median', 'gross_mthly_25_percentile', 'gross_mthly_75_percentile'], axis=1)

print(f'Shape of df in its original form = {df.shape}')
print(f'Shape of df1 after dropping unwanted columns = {df1.shape}')
df1.head(2)

Shape of df in its original form = (289, 12)
Shape of df1 after dropping unwanted columns = (289, 5)


year                        university  \
0  2013  Nanyang Technological University   
1  2013  Nanyang Technological University   

                                        degree gross_monthly_mean  \
0                     Accountancy and Business               3727   
1  Accountancy (3-yr direct Honours Programme)               2938   

  gross_monthly_median  
0                 3350  
1                 2700

In [76]:
# testing different ways:
#df2_test1 = df1[df1.university == 'Nanyang Technological University']
#df2_test2 = df1[df1.university.isin(['Nanyang Technological University'])]

#df2 = df1[df1.university != 'Nanyang Technological University']
#df2

#df2 = df1.university.isin(["Nanyang Technological University", 
"Singapore Institute of Technology", "Singapore University of Technology and Design"])
#df2

In [79]:
# task 7A-2
#df2_test1 = df1[df1.university == 'Nanyang Technological University']
#df2_test2 = df1[df1.university.isin(['Nanyang Technological University'])]

df2 = df1.drop(df1[df1.university.isin(["Nanyang Technological University", "Singapore Institute of Technology", 
                                        "Singapore University of Technology and Design"])].index, inplace = False)
print(f'Shape of df after dropping unwanted rows (universities) = {df2.shape}')
df2.head(2)

Shape of df after dropping unwanted rows (universities) = (154, 5)


year                        university                   degree  \
34  2013  National University of Singapore         Bachelor of Arts   
35  2013  National University of Singapore  Bachelor of Arts (Hons)   

   gross_monthly_mean gross_monthly_median  
34               2888                 2800  
35               3154                 3200

In [87]:
# task 7A-3
df3 = df2.drop(df2[df2.year.isin([2013, 2014])].index, inplace = False)
print(f'Shape of df after dropping unwanted rows (year) = {df3.shape}')
df3.head(2)

Shape of df after dropping unwanted colums (year) = (52, 5)


year                        university                   degree  \
233  2015  National University of Singapore         Bachelor of Arts   
234  2015  National University of Singapore  Bachelor of Arts (Hons)   

    gross_monthly_mean gross_monthly_median  
233               2999                 3000  
234               3310                 3310

In [99]:
# task 7A-4

df4 = df3.drop(df3[df3.gross_monthly_median < '4000'].index, inplace = False)

print(f'Shape of df after dropping unwanted rows (gross_monthly_media) = {df4.shape}')
print()
print(f'*** Final data after all the drops ***')
df4

Shape of df after dropping unwanted rows (gross_monthly_media) = (11, 5)

*** Final data after all the drops ***


year                        university  \
241  2015  National University of Singapore   
242  2015  National University of Singapore   
246  2015  National University of Singapore   
247  2015  National University of Singapore   
254  2015  National University of Singapore   
261  2015  National University of Singapore   
262  2015  National University of Singapore   
266  2015  National University of Singapore   
270  2015  National University of Singapore   
283  2015   Singapore Management University   
284  2015   Singapore Management University   

                                               degree gross_monthly_mean  \
241  Bachelor of Computing (Computational Biology) **                 na   
242   Bachelor of Computing (Computer Engineering) **                 na   
246                        Bachelor of Dental Surgery               4083   
247                Bachelor of Arts (Architecture) ##               4099   
254    Bachelor of Engineering (Computer Engineering)               4252   
261                Bachelor of Laws (L.L.B) (Hons) ##               4910   
262   Bachelor of Medicine and Bachelor of Surgery ##               4729   
266                    Bachelor of Applied Science **                 na   
270    Bachelor of Science (Computational Biology) **                 na   
283                                            Law ++               4997   
284                           Law Cum Laude and above               5313   

    gross_monthly_median  
241                   na  
242                   na  
246                 4000  
247                 4127  
254                 4000  
261                 4700  
262                 4900  
266                   na  
270                   na  
283                 4731  
284                 5000

In [28]:
# task 7B-1
df_arts = pd.DataFrame(pd.read_csv('data/pa-performing-arts-courses.csv'))
df_sports = pd.DataFrame(pd.read_csv('data/pa-sports-courses.csv'))

print(f'***** With Performing Art Courses Data only *****')
print(f'df_art.shape: {df_arts.shape}'); print(df_arts[:2]); print(df_arts[-2:])
print()

print(f'***** With Sports Courses Data only *****')
print(f'df_sports.shape: {df_sports.shape}'); print(df_sports[:2]); print(df_sports[-2:])
print()

df_all = pd.concat([df_arts,df_sports])
print(f'***** After concatemating the two DataFrame objects *****')
print(f'df_all.shape: {df_all.shape}'); print(df_all[:3]); print(df_all[-3:])

***** With Performing Art Courses Data only *****
df_art.shape: (28, 3)
   year type_of_courses  no_of_classes
0  2009           Dance           8628
1  2009           Drama            440
    year type_of_courses  no_of_classes
26  2015           Music           6376
27  2015           Vocal           2922

***** With Sports Courses Data only *****
df_sports.shape: (42, 3)
   year             type_of_courses  no_of_classes
0  2009                  Ball Games            511
1  2009  Board / Intellectual Games             24
    year    type_of_courses  no_of_classes
40  2015  Performing Sports            530
41  2015       Water Sports           2279

***** After concatemating the two DataFrame objects *****
df_all.shape: (70, 3)
   year type_of_courses  no_of_classes
0  2009           Dance           8628
1  2009           Drama            440
2  2009           Music           7668
    year    type_of_courses  no_of_classes
39  2015       Martial Arts           4533
40  2015  Performi

In [32]:
# task 7C-1
mydf = pd.DataFrame(pd.read_csv('data/irascollectionbytaxtype.csv'))

print(f'***** The first 10 rows of the IRAS collection from 2002 to 2016 *****')
print(mydf[:10])
print()

mydf_sortby = mydf.sort_values(by="tax_collected",ascending=False)
mydf_sortby

print(f'***** Top 10 IRAS collection *****')
print()
print(mydf_sortby[:10]); print()

print(f'***** Bottom 10 IRAS collection *****')
print()
print(mydf_sortby[-10:])

***** The first 10 rows of the IRAS collection from 2002 to 2016 *****
   financial_year                                           tax_type  \
0            2002                                         Income Tax   
1            2002                             Goods and Services Tax   
2            2002                                       Property Tax   
3            2002                                         Stamp Duty   
4            2002                                      Betting Taxes   
5            2002                                        Estate Duty   
6            2003                  Income Tax - Corporate Income Tax   
7            2003  Income Tax - Individual Income Tax and Withhol...   
8            2003                             Goods and Services Tax   
9            2003                                       Property Tax   

   tax_collected  
0       10876295  
1        2166493  
2        1232593  
3         695437  
4        1549545  
5          75607  
6  

In [54]:
# task 7C-2: Sort DataFrame by index values
mydf = pd.DataFrame(pd.read_csv('data/irascollectionbytaxtype.csv'))

mydf = mydf.set_index(['financial_year','tax_collected'])

print(f'***** The first 10 rows of the IRAS collection fro 2002 to 2016 *****'); print()
print(mydf[:10]); print()

mydf_sorted = mydf.sort_index(level='tax_collected', ascending=False)
print(f'Top 5 Collections'); print()
print(mydf_sorted[:5]); print()

print(f'Bottom 5 Collections'); print()
print(mydf_sorted[-5:]); print()

***** The first 10 rows of the IRAS collection fro 2002 to 2016 *****

                                                                       tax_type
financial_year tax_collected                                                   
2002           10876295                                              Income Tax
               2166493                                   Goods and Services Tax
               1232593                                             Property Tax
               695437                                                Stamp Duty
               1549545                                            Betting Taxes
               75607                                                Estate Duty
2003           5923741                        Income Tax - Corporate Income Tax
               3865164        Income Tax - Individual Income Tax and Withhol...
               2958598                                   Goods and Services Tax
               1331566                           

In [9]:
# TASK 7D-1: Rename the columns of a DataFrame
mydf = (pd.read_csv('data/publictransport.csv'))

print(f'*** Original dataset ***')
print(mydf[:5]);  print()

mydf1=mydf.rename(columns={"year":"Year","type_of_public_transport":"Transport Type",
                          "average_ridership":"Average Ridership",})

print(f'*** Dataset after naming column names ***')
print(mydf1[:5]);

*** Original dataset ***
   year type_of_public_transport  average_ridership
0  1995                      MRT             740000
1  1995                      LRT                  0
2  1995                      Bus            3009000
3  1995                     Taxi                  0
4  1996                      MRT             850000

*** Dataset after naming column names ***
   Year Transport Type  Average Ridership
0  1995            MRT             740000
1  1995            LRT                  0
2  1995            Bus            3009000
3  1995           Taxi                  0
4  1996            MRT             850000


# Task 8. Handling missing data  

Making a list of missing value types, Pandas recognized the “NA” as a missing value. Unfortunately, the other types weren’t recognized. An easy way to detect these various formats is to put them in a list. 
#Then when we import the data, Pandas will recognize them right away

#missing_values = ["n/a", "na", "--", "-"]
#df = pd.read_excel('data/singstats_maritalstatus.xlsx', na_values = missing_values)

In [29]:
# task 8A-1
import pandas as pd

mydf = pd.read_excel('data/singstats_maritalstatus.xlsx', index_col='Variables', na_values='-')

df_missing = mydf.isnull()

print(f'***** Use isnull to see if a column or row contain data *****')
print(df_missing.iloc[:,:8])

***** Use isnull to see if a column or row contain data *****
                      1980  1981  1982   1983   1984   1985   1986   1987
Variables                                                                
Total                False  True  True  False  False  False  False  False
Single               False  True  True  False  False  False  False  False
Married              False  True  True  False  False  False  False  False
Widowed              False  True  True  False  False  False  False  False
Divorced/ Separated  False  True  True  False  False  False  False  False
Males                False  True  True  False  False  False  False  False
Single               False  True  True  False  False  False  False  False
Married              False  True  True  False  False  False  False  False
Widowed              False  True  True  False  False  False  False  False
Divorced/ Separated  False  True  True  False  False  False  False  False
Females              False  True  True  False  Fal

In [8]:
# task 8B-1: Drop missing values with dropna

mydf = pd.read_excel('data/singstats_maritalstatus.xlsx', index_col='Variables', na_values='-')

print(f'**** First 10 rows of original dataset ****')
print(mydf.iloc[:10,:7]);  print()

mydf1 = mydf.isnull()
mydf2 = mydf.dropna(axis=1)
print(f'**** Remaining dataset after dropping columns with missing data ****')
print(mydf2.iloc[:10,:6]);

**** First 10 rows of original dataset ****
                        1980  1981  1982     1983     1984     1985     1986
Variables                                                                   
Total                1651500   NaN   NaN  1791900  1829000  1866700  1906600
Single                674100   NaN   NaN   728000   714300   726600   736500
Married               864600   NaN   NaN   951200  1005100  1020100  1039700
Widowed                97100   NaN   NaN   101700    92800    99200   108200
Divorced/ Separated    15800   NaN   NaN    11000    16700    20800    22300
Males                 833500   NaN   NaN   901700   912200   929800   948000
Single                375800   NaN   NaN   404700   393400   400100   408100
Married               435900   NaN   NaN   476300   499600   506500   517100
Widowed                16000   NaN   NaN    16600    13600    16200    15500
Divorced/ Separated     5700   NaN   NaN     4100     5600     7000     7300

**** Remaining dataset after dr

In [83]:
# task 8C-1: Drop missing values with dropna
mydf = pd.DataFrame(pd.read_csv('data/hdbresaleindex_missing.csv', index_col='quarter'))

print(f'***** First 10 rows of original dataswet *****')
print(mydf.iloc[:10]);  print()

print(f'The sum of the null cells count: {sum(mydf.isnull().any(axis=1))}')
print()

df_missing = mydf[mydf.isnull().any(axis=1)]
print(f'**** Rows with missing values -- df_missing ****')
print(df_missing);  print()


df1 = mydf.fillna(50.0)
print(f'***** Dataset after scalar fill operation *****')
print(df1.iloc[:12]);  print()

df2 = mydf.fillna(method='pad')
print(f'***** Dataset after forward fill operation *****')
print(df2.iloc[:12]);  print()

df3 = mydf.fillna(method='bfill')
print(f'***** Dataset after backward fill operation *****')
print(df3.iloc[:12]);  print()

df4 = mydf.fillna(mydf.mean(axis=0))
print(f'***** Dataset after filling with means *****')
print(df4.iloc[:12]);  print()


***** First 10 rows of original dataswet *****
         index
quarter       
1990-Q1   24.3
1990-Q2   24.4
1990-Q3   25.0
1990-Q4   24.7
1991-Q1   24.9
1991-Q2   25.5
1991-Q3   25.2
1991-Q4   25.1
1992-Q1   25.8
1992-Q2    NaN

The sum of the null cells count: 5

**** Rows with missing values -- df_missing ****
         index
quarter       
1992-Q2    NaN
1998-Q2    NaN
2003-Q4    NaN
2013-Q4    NaN
2016-Q1    NaN

***** Dataset after scalar fill operation *****
         index
quarter       
1990-Q1   24.3
1990-Q2   24.4
1990-Q3   25.0
1990-Q4   24.7
1991-Q1   24.9
1991-Q2   25.5
1991-Q3   25.2
1991-Q4   25.1
1992-Q1   25.8
1992-Q2   50.0
1992-Q3   28.0
1992-Q4   28.6

***** Dataset after forward fill operation *****
         index
quarter       
1990-Q1   24.3
1990-Q2   24.4
1990-Q3   25.0
1990-Q4   24.7
1991-Q1   24.9
1991-Q2   25.5
1991-Q3   25.2
1991-Q4   25.1
1992-Q1   25.8
1992-Q2   25.8
1992-Q3   28.0
1992-Q4   28.6

***** Dataset after backward fill operation *****
         ind

# Task 9.	Combine datasets

In [176]:
# task 9A-1
df_m = pd.DataFrame(pd.read_csv('data\merge_students-male.csv'))
df_f = pd.DataFrame(pd.read_csv('data\merge_students-female.csv'))
df_test = pd.DataFrame(pd.read_csv('data/merge_testscores.csv'))

df_students = pd.concat([df_m,df_f])
df_merged = pd.merge(df_students, df_test, on='studentid', how="inner")

df_students
df_merged

studentid LastName  FirstName Gender  test score
0       1500001     Chan     George      M          50
1       1500005     Choo    Leonard      M          32
2       1500006       Ho    Richard      M          23
3       1500007     Seah      James      M          94
4       1500008      Tan      James      M          59
...         ...      ...        ...    ...         ...
1002    1500992       Ng    Natalie      F          92
1003    1500995      Lee  Magdalene      F          80
1004    1500996     Chua        Uma      F          99
1005    1500997     Chan      Clara      F          72
1006    1500998     Wong      Karen      F          81

[1007 rows x 5 columns]

In [173]:
df_test

studentid  test score
0      1500130          79
1      1500767          31
2      1500468          78
3      1500220          27
4      1500691          65
..         ...         ...
995    1500195          63
996    1500432          22
997    1500704          36
998    1500633          38
999    1501000          41

[1000 rows x 2 columns]

In [175]:
# task 9A-1
df_merged = pd.merge(df_students, df_test, on='studentid', how="inner")

df_merged

studentid LastName  FirstName Gender  test score
0       1500001     Chan     George      M          50
1       1500005     Choo    Leonard      M          32
2       1500006       Ho    Richard      M          23
3       1500007     Seah      James      M          94
4       1500008      Tan      James      M          59
...         ...      ...        ...    ...         ...
1002    1500992       Ng    Natalie      F          92
1003    1500995      Lee  Magdalene      F          80
1004    1500996     Chua        Uma      F          99
1005    1500997     Chan      Clara      F          72
1006    1500998     Wong      Karen      F          81

[1007 rows x 5 columns]